# Generated by Django 5.2 on 2025-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Chef', 'Chef'), ('DeliveryBoy', 'Delivery Boy'), ('Other', 'Other')], max_length=20)),
                ('custom_role', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resigned', 'Resigned')], default='Active', max_length=20)),
                ('salary', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
            ],
        ),
    ]
