# Generated by Django 5.2 on 2025-09-10 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_staff_salary_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
